title: kriscarilloxyz — software engineer
email: kriscarilloxyz@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Kristofferson Carillo — software engineer based in the Philippines.


baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:title
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Accounts
twitter_username: kriscarilloxyz
github_username:  kriscarilloxyz

# Build settings
plugins:
  - jekyll-feed